name: pugo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyter
